---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    #vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(leaflet)
library(DT)

source("CMAS_Clean_shiny.R", echo = TRUE)

load_vars()

countyshapes_url <- "http://www2.census.gov/geo/tiger/GENZ2016/shp/cb_2016_us_county_20m.zip"
if (!dir.exists("data")) {dir.create("data")}
if (!file.exists("data/county_shape_file.zip")) {
  download.file(countyshapes_url
                , destfile = "data/county_shape_file.zip")
    }

c_shp <- unzip(zipfile = 'data/county_shape_file.zip',
               exdir = 'data')

counties_sf <- read_sf(c_shp[grep("shp$", c_shp)]) %>%
  as.data.frame() %>% #to fix July 25 problem with the join.sf methods
  inner_join(lsad_lookup()) %>%
    select(STATEFP, COUNTYFP, GEOID, NAME, description, geometry) %>%
    left_join(state_sf %>% select(STATEFP, STUSPS)) %>%
  st_sf(sf_column_name = 'geometry') %>%
  st_transform('+proj=longlat +datum=WGS84')

file.remove(c_shp)

```

Row 
-----------------------------------------------------------------------

### Chart A

```{r}

```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Chart B

```{r}

```

### Chart C

```{r}

```

